export const SOCKET_LOBBY_SERVER = 'SOCKET_LOBBY_SERVER';
export const SOCKET_LOBBY_CLIENT = 'SOCKET_LOBBY_CLIENT';

export const LOBBY_ACTION_SET_STEP = 'LOBBY_ACTION_SET_STEP';
export const LOBBY_STEP_NICKNAME = 'LOBBY_STEP_NICKNAME';
export const LOBBY_STEP_ROOM_SELECTION = 'LOBBY_STEP_ROOM_SELECTION';

export const SOCKET_ON_LOBBY_STEP_CHANGE = 'SOCKET_ON_LOBBY_STEP_CHANGE';
export const SOCKET_ON_NICKNAME_CHANGE = 'SOCKET_ON_NICKNAME_CHANGE';
export const SOCKET_ON_ROOM_LIST = 'SOCKET_ON_ROOM_LIST';
export const SOCKET_ON_ROOM_ADD = 'SOCKET_ON_ROOM_ADD';
export const SOCKET_ON_ROOM_JOIN = 'SOCKET_ON_ROOM_JOIN';
export const SOCKET_ON_ROOM_LEAVE = 'SOCKET_ON_ROOM_LEAVE';
export const SOCKET_ON_ROOM = 'SOCKET_ON_ROOM';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
export const SOCKET_ON_CHAT = 'SOCKET_ON_CHAT';
export const SOCKET_ON_WORD_SELECT = 'SOCKET_ON_WORD_SELECT';
export const SOCKET_ON_PAINT = 'SOCKET_ON_PAINT';

export const DESK_WIDTH = 600;
export const DESK_HEIGHT = 400;

export const ROOM_STATUS_WAITING = 'ROOM_STATUS_WAITING';
export const ROOM_STATUS_PAINTER_SELECTING = 'ROOM_STATUS_PAINTER_SELECTING';
export const ROOM_STATUS_WORD_SELECTING = 'ROOM_STATUS_WORD_SELECTING';
export const ROOM_STATUS_DRAWING = 'ROOM_STATUS_DRAWING';
export const ROOM_STATUS_GAME_FINISHED = 'ROOM_STATUS_GAME_FINISHED';